version: "3"
services:
  db:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: debtClearTest!Passw0rd
      MYSQL_DATABASE: debtClearFlow
      MYSQL_USER: egor
      MYSQL_PASSWORD: debtClearTest!Passw0rd
    ports:
      - "3307:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: debtClearTest!Passw0rd
